export const TOOL_GROUP_DESCRIPTIONS = {
  country_data: "Country profiles from REST Countries.",
  dictionary: "Definitions, synonyms, antonyms, rhymes, and autocomplete.",
  books: "Open Library and Gutendex book lookups.",
  university_data: "University search by name and country.",
  geocoding: "Forward geocoding, reverse geocoding, and postal lookups.",
  ip_geolocation: "IP lookup for city, region, timezone, and network data.",
  currency_exchange: "Currency rates, conversions, and historical series.",
  crypto_data: "CoinGecko-powered crypto market data.",
  stock_market: "Quotes, symbol search, SEC filings, and FRED data.",
  weather: "Forecasts, current conditions, alerts, and sun times.",
  air_quality: "Air quality and UK carbon intensity data.",
  carbon_footprint: "Carbon Interface estimates for activities.",
  http_utils: "HTTP introspection, QR codes, epoch, timezone, and IP utilities.",
  dns_network: "DNS lookup and reverse DNS via Cloudflare.",
  code_execution: "Remote code execution via Judge0.",
  placeholder_data: "Synthetic users, posts, lorem ipsum, avatars, and UUIDs.",
  translation: "Translation and language detection via LibreTranslate.",
  data_validation: "Profanity filtering and content checks.",
  wikipedia: "Wikipedia and Wikidata search helpers.",
  news: "Spaceflight News API.",
  tech_news: "HackerNews, Dev.to, and tech headlines.",
  dev_tools: "npm registry, GitHub, and CDNJS developer lookups.",
  images: "Lorem Picsum image placeholders.",
  music_data: "MusicBrainz, iTunes, artist detail, radio, and genre helpers.",
  movie_tv_data: "Movies, TV, anime, schedules, and franchise lookups.",
  game_data: "Games, cards, RPG, chess puzzles, and trivia datasets.",
  math: "Symbolic math and number facts.",
  space: "NASA, ISS tracking, Mars photos, SpaceX, and earthquake data.",
  food_recipes: "Food, drinks, breweries, and fruit data.",
  random_facts: "Jokes, quotes, trivia, xkcd, and novelty text feeds.",
  animals: "Animal facts, breeds, images, and wildlife data.",
  email_validation: "Email deliverability and reputation helpers.",
  name_insights: "Gender, age, and nationality predictions from names.",
  security_intel: "Vulnerability, Shodan InternetDB, and police/open threat feeds.",
  blockchain: "Bitcoin, mempool statistics, and Solana data.",
  holidays: "Public holidays and UK bank holidays.",
  job_search: "Arbeitnow job board search.",
  transport: "Flight tracking, bike share networks, and EV charging data.",
  government_data: "Wanted lists, notices, registers, and Census Bureau data.",
  health_data: "FDA, USDA, and NPI registry lookups.",
  open_data: "Open civic, culture, sport, and archive datasets.",
} as const;

export type ToolGroupKey = keyof typeof TOOL_GROUP_DESCRIPTIONS;