export const TOOL_GROUP_DESCRIPTIONS = {
  country_data: "Country profiles from REST Countries.",
  dictionary: "Definitions, synonyms, antonyms, rhymes, and autocomplete.",
  books: "Books, Gutenberg titles, and poetry lookups.",
  university_data: "University search by name and country.",
  geocoding: "Forward geocoding, reverse geocoding, and postal lookups.",
  ip_geolocation: "IP lookup for city, region, timezone, and network data.",
  currency_exchange: "Currency rates, conversions, and historical series.",
  crypto_data: "CoinGecko-powered crypto market data.",
  stock_market: "Quotes, symbol search, SEC filings, and FRED data.",
  weather: "Forecasts, current conditions, alerts, and sun times.",
  air_quality: "Air quality, UK carbon intensity, and website carbon data.",
  carbon_footprint: "Carbon Interface estimates for activities.",
  http_utils: "HTTP introspection, QR codes, URL shortening, and protocol checks.",
  dns_network: "DNS, subnet, and domain search utilities.",
  code_execution: "Remote code execution via Wandbox.",
  placeholder_data: "Synthetic users, posts, lorem ipsum, avatars, and UUIDs.",
  screenshot: "Website screenshot metadata via Microlink.",
  translation: "Translation, language detection, and novelty translators.",
  text_analysis: "Profanity filtering and text safety checks.",
  wikipedia: "Wikipedia and Wikidata search helpers.",
  news: "Spaceflight and historic newspaper APIs.",
  images: "Lorem Picsum image placeholders.",
  music_data: "MusicBrainz, iTunes, lyrics, radio, and genre helpers.",
  movie_tv_data: "Movies, TV, anime, sci-fi, and franchise lookups.",
  math: "Symbolic math and number facts.",
  space: "NASA, ISS, launches, SpaceX, and earthquake data.",
  food_recipes: "Food, drinks, breweries, beer, and fruit data.",
  random_facts: "Jokes, quotes, trivia, xkcd, and novelty text feeds.",
  animals: "Animal images, facts, and marine-life data.",
  game_data: "Games, cards, RPG, anime, and trivia datasets.",
  email_validation: "Email deliverability and reputation helpers.",
  phone_validation: "Phone device catalog lookups.",
  data_validation: "Content validation helpers.",
  security_intel: "Vulnerability, phishing, and police/open threat feeds.",
  blockchain: "Bitcoin, Helium, and Solana data.",
  holidays: "Public holidays, bank holidays, and namedays.",
  job_search: "Job board search results.",
  transport: "Flight, bike share, EV charging, and transit endpoints.",
  government_data: "Wanted lists, notices, registers, and civic datasets.",
  health_data: "FDA, USDA, and NPI registry lookups.",
  open_data: "Open civic, culture, sport, and city quality datasets.",
} as const;

export type ToolGroupKey = keyof typeof TOOL_GROUP_DESCRIPTIONS;
